<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="dashboard_granos-20240502180732" tests="1" file=".py" time="33.212" timestamp="2024-05-02T18:08:05" failures="0" errors="1" skipped="0">
	<testcase classname="dashboard_granos" name="test_dashboard_grain" time="33.212" timestamp="2024-05-02T18:08:05" file="DashboarGranos.py" line="23">
		<error type="TypeError" message="calendar_ansterdate() takes 2 positional arguments but 3 were given"><![CDATA[Traceback (most recent call last):
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\DashboarGranos.py", line 58, in test_dashboard_grain
    calendar_ansterdate(self.driver, select_data_aster, popup_calendar2)
TypeError: calendar_ansterdate() takes 2 positional arguments but 3 were given
]]></error>
	</testcase>
</testsuite>
