<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="HomeTenant-20231219175516" tests="1" file=".py" time="19.998" timestamp="2023-12-19T17:55:36" failures="0" errors="1" skipped="0">
	<testcase classname="HomeTenant" name="test_inicio_tenant" time="19.998" timestamp="2023-12-19T17:55:36" file="Home.py" line="21">
		<error type="NoSuchWindowException" message="Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=120.0.6099.110)
Stacktrace:
	GetHandleVerifier [0x00007FF6091E2142+3514994]
	(No symbol) [0x00007FF608E00CE2]
	(No symbol) [0x00007FF608CA76AA]
	(No symbol) [0x00007FF608C80AFD]
	(No symbol) [0x00007FF608D1CB1B]
	(No symbol) [0x00007FF608D3218F]
	(No symbol) [0x00007FF608D15D93]
	(No symbol) [0x00007FF608CE4BDC]
	(No symbol) [0x00007FF608CE5C64]
	GetHandleVerifier [0x00007FF60920E16B+3695259]
	GetHandleVerifier [0x00007FF609266737+4057191]
	GetHandleVerifier [0x00007FF60925E4E3+4023827]
	GetHandleVerifier [0x00007FF608F304F9+689705]
	(No symbol) [0x00007FF608E0C048]
	(No symbol) [0x00007FF608E08044]
	(No symbol) [0x00007FF608E081C9]
	(No symbol) [0x00007FF608DF88C4]
	BaseThreadInitThunk [0x00007FFBA8B3257D+29]
	RtlUserThreadStart [0x00007FFBA8E8AA58+40]
"><![CDATA[Traceback (most recent call last):
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\Home.py", line 28, in test_inicio_tenant
    Filtro_campaÃ±a = self.driver.find_element(By.XPATH,"/html/body/app-root/app-layout/app-vertical/div/div/div/div/app-home/div/div[2]/app-business-indicators/div[1]/div[2]/app-filter-button/button/div/span")
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 742, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=120.0.6099.110)
Stacktrace:
	GetHandleVerifier [0x00007FF6091E2142+3514994]
	(No symbol) [0x00007FF608E00CE2]
	(No symbol) [0x00007FF608CA76AA]
	(No symbol) [0x00007FF608C80AFD]
	(No symbol) [0x00007FF608D1CB1B]
	(No symbol) [0x00007FF608D3218F]
	(No symbol) [0x00007FF608D15D93]
	(No symbol) [0x00007FF608CE4BDC]
	(No symbol) [0x00007FF608CE5C64]
	GetHandleVerifier [0x00007FF60920E16B+3695259]
	GetHandleVerifier [0x00007FF609266737+4057191]
	GetHandleVerifier [0x00007FF60925E4E3+4023827]
	GetHandleVerifier [0x00007FF608F304F9+689705]
	(No symbol) [0x00007FF608E0C048]
	(No symbol) [0x00007FF608E08044]
	(No symbol) [0x00007FF608E081C9]
	(No symbol) [0x00007FF608DF88C4]
	BaseThreadInitThunk [0x00007FFBA8B3257D+29]
	RtlUserThreadStart [0x00007FFBA8E8AA58+40]

]]></error>
	</testcase>
</testsuite>
