<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="InicioTenant-20231210190040" tests="1" file=".py" time="5.918" timestamp="2023-12-10T19:00:46" failures="0" errors="1" skipped="0">
	<testcase classname="InicioTenant" name="test_inicio_tenant" time="5.918" timestamp="2023-12-10T19:00:46" file="inicio.py" line="26">
		<error type="NameError" message="name 'Keys' is not defined"><![CDATA[Traceback (most recent call last):
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\inicio.py", line 28, in test_inicio_tenant
    self.login_helper.login("admingd@silohub.ag", "G@viglio123")
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\loginhelper.py", line 13, in login
    self.driver.find_element(By.XPATH, "/html/body/app-root/app-login-main/div/div[2]/div/app-login-form/div/div/div[1]/div/div[2]/form/div[4]/app-button/button").send_keys(Keys.ENTER)
NameError: name 'Keys' is not defined
]]></error>
	</testcase>
</testsuite>
