<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="cuenta_entregas-20231212182452" tests="1" file=".py" time="29.658" timestamp="2023-12-12T18:25:22" failures="0" errors="1" skipped="0">
	<testcase classname="cuenta_entregas" name="test_cuenta_entregas" time="29.658" timestamp="2023-12-12T18:25:22" file="Entregas.py" line="35">
		<error type="StaleElementReferenceException" message="Message: stale element reference: stale element not found
  (Session info: chrome=120.0.6099.71); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
	GetHandleVerifier [0x00007FF783484D02+56194]
	(No symbol) [0x00007FF7833F04B2]
	(No symbol) [0x00007FF7832976AA]
	(No symbol) [0x00007FF78329CFC0]
	(No symbol) [0x00007FF78329F38F]
	(No symbol) [0x00007FF78329F480]
	(No symbol) [0x00007FF7832E33D9]
	(No symbol) [0x00007FF7832E27D6]
	(No symbol) [0x00007FF7832D687F]
	(No symbol) [0x00007FF783305E7A]
	(No symbol) [0x00007FF7832D6226]
	(No symbol) [0x00007FF783306320]
	(No symbol) [0x00007FF783322786]
	(No symbol) [0x00007FF783305C23]
	(No symbol) [0x00007FF7832D4A45]
	(No symbol) [0x00007FF7832D5AD4]
	GetHandleVerifier [0x00007FF7837FD5BB+3695675]
	GetHandleVerifier [0x00007FF783856197+4059159]
	GetHandleVerifier [0x00007FF78384DF63+4025827]
	GetHandleVerifier [0x00007FF78351F029+687785]
	(No symbol) [0x00007FF7833FB508]
	(No symbol) [0x00007FF7833F7564]
	(No symbol) [0x00007FF7833F76E9]
	(No symbol) [0x00007FF7833E8094]
	BaseThreadInitThunk [0x00007FFB1102257D+29]
	RtlUserThreadStart [0x00007FFB1232AA58+40]
"><![CDATA[Traceback (most recent call last):
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\Entregas.py", line 46, in test_cuenta_entregas
    select_menu_Account.click()
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webelement.py", line 93, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webelement.py", line 394, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found
  (Session info: chrome=120.0.6099.71); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
	GetHandleVerifier [0x00007FF783484D02+56194]
	(No symbol) [0x00007FF7833F04B2]
	(No symbol) [0x00007FF7832976AA]
	(No symbol) [0x00007FF78329CFC0]
	(No symbol) [0x00007FF78329F38F]
	(No symbol) [0x00007FF78329F480]
	(No symbol) [0x00007FF7832E33D9]
	(No symbol) [0x00007FF7832E27D6]
	(No symbol) [0x00007FF7832D687F]
	(No symbol) [0x00007FF783305E7A]
	(No symbol) [0x00007FF7832D6226]
	(No symbol) [0x00007FF783306320]
	(No symbol) [0x00007FF783322786]
	(No symbol) [0x00007FF783305C23]
	(No symbol) [0x00007FF7832D4A45]
	(No symbol) [0x00007FF7832D5AD4]
	GetHandleVerifier [0x00007FF7837FD5BB+3695675]
	GetHandleVerifier [0x00007FF783856197+4059159]
	GetHandleVerifier [0x00007FF78384DF63+4025827]
	GetHandleVerifier [0x00007FF78351F029+687785]
	(No symbol) [0x00007FF7833FB508]
	(No symbol) [0x00007FF7833F7564]
	(No symbol) [0x00007FF7833F76E9]
	(No symbol) [0x00007FF7833E8094]
	BaseThreadInitThunk [0x00007FFB1102257D+29]
	RtlUserThreadStart [0x00007FFB1232AA58+40]

]]></error>
	</testcase>
</testsuite>
