<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="HomeTenant-20240510163844" tests="1" file=".py" time="240.286" timestamp="2024-05-10T16:42:44" failures="0" errors="1" skipped="0">
	<testcase classname="HomeTenant" name="test_start_tenant" time="240.286" timestamp="2024-05-10T16:42:44" file="Home.py" line="19">
		<error type="NoSuchWindowException" message="Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=124.0.6367.156)
Stacktrace:
	GetHandleVerifier [0x00007FF7F3371562+60802]
	(No symbol) [0x00007FF7F32EAC62]
	(No symbol) [0x00007FF7F31A7CE4]
	(No symbol) [0x00007FF7F317DFDF]
	(No symbol) [0x00007FF7F3221E57]
	(No symbol) [0x00007FF7F32398D1]
	(No symbol) [0x00007FF7F321A923]
	(No symbol) [0x00007FF7F31E8FEC]
	(No symbol) [0x00007FF7F31E9C21]
	GetHandleVerifier [0x00007FF7F36741FD+3217949]
	GetHandleVerifier [0x00007FF7F36B6197+3488183]
	GetHandleVerifier [0x00007FF7F36AF11F+3459391]
	GetHandleVerifier [0x00007FF7F342B926+823622]
	(No symbol) [0x00007FF7F32F5FFF]
	(No symbol) [0x00007FF7F32F0F24]
	(No symbol) [0x00007FF7F32F10B2]
	(No symbol) [0x00007FF7F32E1904]
	BaseThreadInitThunk [0x00007FFEC3DD257D+29]
	RtlUserThreadStart [0x00007FFEC4CAAA48+40]
"><![CDATA[Traceback (most recent call last):
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\Home.py", line 47, in test_start_tenant
    validate_text(self.driver, page_hello, text_expected  )
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\Elements.py", line 459, in validate_text
    valor = elemento.text
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webelement.py", line 90, in text
    return self._execute(Command.GET_ELEMENT_TEXT)["value"]
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=124.0.6367.156)
Stacktrace:
	GetHandleVerifier [0x00007FF7F3371562+60802]
	(No symbol) [0x00007FF7F32EAC62]
	(No symbol) [0x00007FF7F31A7CE4]
	(No symbol) [0x00007FF7F317DFDF]
	(No symbol) [0x00007FF7F3221E57]
	(No symbol) [0x00007FF7F32398D1]
	(No symbol) [0x00007FF7F321A923]
	(No symbol) [0x00007FF7F31E8FEC]
	(No symbol) [0x00007FF7F31E9C21]
	GetHandleVerifier [0x00007FF7F36741FD+3217949]
	GetHandleVerifier [0x00007FF7F36B6197+3488183]
	GetHandleVerifier [0x00007FF7F36AF11F+3459391]
	GetHandleVerifier [0x00007FF7F342B926+823622]
	(No symbol) [0x00007FF7F32F5FFF]
	(No symbol) [0x00007FF7F32F0F24]
	(No symbol) [0x00007FF7F32F10B2]
	(No symbol) [0x00007FF7F32E1904]
	BaseThreadInitThunk [0x00007FFEC3DD257D+29]
	RtlUserThreadStart [0x00007FFEC4CAAA48+40]

]]></error>
	</testcase>
</testsuite>
