<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="CtaCtoDtalLiquidaciones.detalle_cto_liquidaciones-failed" tests="1" file="CtaCtoDtalLiquidaciones.py" time="59.922" timestamp="2024-06-06T12:46:13" failures="0" errors="1" skipped="0">
	<testcase classname="CtaCtoDtalLiquidaciones.detalle_cto_liquidaciones" name="test_detail_liquidations" time="59.922" timestamp="2024-06-06T12:46:13" file="CtaCtoDtalLiquidaciones.py" line="22">
		<error type="NoSuchWindowException" message="Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=125.0.6422.142)
Stacktrace:
	GetHandleVerifier [0x00007FF6A6381F52+60322]
	(No symbol) [0x00007FF6A62FCEC9]
	(No symbol) [0x00007FF6A61B7EBA]
	(No symbol) [0x00007FF6A618D5A5]
	(No symbol) [0x00007FF6A62336B7]
	(No symbol) [0x00007FF6A624B331]
	(No symbol) [0x00007FF6A622BFC3]
	(No symbol) [0x00007FF6A61F9617]
	(No symbol) [0x00007FF6A61FA211]
	GetHandleVerifier [0x00007FF6A66994AD+3301629]
	GetHandleVerifier [0x00007FF6A66E36D3+3605283]
	GetHandleVerifier [0x00007FF6A66D9450+3563680]
	GetHandleVerifier [0x00007FF6A6434326+790390]
	(No symbol) [0x00007FF6A630750F]
	(No symbol) [0x00007FF6A6303404]
	(No symbol) [0x00007FF6A6303592]
	(No symbol) [0x00007FF6A62F2F9F]
	BaseThreadInitThunk [0x00007FFBED37257D+29]
	RtlUserThreadStart [0x00007FFBEECEAA48+40]
"><![CDATA[Traceback (most recent call last):
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\CtaCtoDtalLiquidaciones.py", line 92, in test_detail_liquidations
    validate_text_by_text(self.driver, text_expected)
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\Elements.py", line 1000, in validate_text_by_text
    elemento = WebDriverWait(driver, 10).until(
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\support\expected_conditions.py", line 84, in _predicate
    return driver.find_element(*locator)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 742, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=125.0.6422.142)
Stacktrace:
	GetHandleVerifier [0x00007FF6A6381F52+60322]
	(No symbol) [0x00007FF6A62FCEC9]
	(No symbol) [0x00007FF6A61B7EBA]
	(No symbol) [0x00007FF6A618D5A5]
	(No symbol) [0x00007FF6A62336B7]
	(No symbol) [0x00007FF6A624B331]
	(No symbol) [0x00007FF6A622BFC3]
	(No symbol) [0x00007FF6A61F9617]
	(No symbol) [0x00007FF6A61FA211]
	GetHandleVerifier [0x00007FF6A66994AD+3301629]
	GetHandleVerifier [0x00007FF6A66E36D3+3605283]
	GetHandleVerifier [0x00007FF6A66D9450+3563680]
	GetHandleVerifier [0x00007FF6A6434326+790390]
	(No symbol) [0x00007FF6A630750F]
	(No symbol) [0x00007FF6A6303404]
	(No symbol) [0x00007FF6A6303592]
	(No symbol) [0x00007FF6A62F2F9F]
	BaseThreadInitThunk [0x00007FFBED37257D+29]
	RtlUserThreadStart [0x00007FFBEECEAA48+40]

]]></error>
		<system-out><![CDATA[¡Elemento encontrado y clickeado 5 veces con éxito!
¡Elemento encontrado y clickeado 2 veces con éxito!
¡Elemento encontrado y clickeado 3 veces con éxito!
]]></system-out>
	</testcase>
</testsuite>
